import Navigation from "@/components/Navigation/Navigation";
import Footer from "@/components/Navigation/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div
          className="pt-10"
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
